
# add "create patch release" or "create minor release" or "create major release"

name: "release workflow"
on:
  push:
    branches:
      - master
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "setup" # check: https://github.com/actions/virtual-environments/issues/1777
        uses: denolib/setup-deno@v2 
        with:
         deno-version: v1.4.6
      - name: "check patch"
        if: contains(github.event.head_commit.message, 'create patch release')
        run: deno run --allow-net https://deno.land/x/cicd/create-patch-release.ts ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }}
      - name: "check minor"
        if: contains(github.event.head_commit.message, 'create minor release')
        run: deno run --allow-net https://deno.land/x/cicd/create-minor-release.ts ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }}
      - name: "check major"
        if: contains(github.event.head_commit.message, 'create major release')
        run: deno run --allow-net https://deno.land/x/cicd/create-major-release.ts ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }}